### ISSUE TITLE
Crash in Subway 1

### ISSUE THREAD

**Issue by AnEternalEnigma** [HunterStanton/SilentHill4Randomizer#1]
Game crashes to desktop after cutscene with Cynthia when entering the next area where the bathroom doors are.

Using the latest GOG build (January 26, 2022) and on Windows 10 Pro

[info.log](https://github.com/HunterStanton/SilentHill4Randomizer/files/8022595/info.log)

**Comment by HunterStanton** [comment]
Fixed by cf6f9a0688259748e60f753f13c4b7093d0d200c
